# Generated by Django 6.0.6 on 2026-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_brand_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
