# Generated by Django 6.0.6 on 2026-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
