# Generated by Django 6.0.6 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
