# Generated by Django 6.0.6 on 2026-06-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
