# Generated by Django 6.0.6 on 2026-06-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
