# Generated by Django 6.0.6 on 2026-06-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_userprofile_address_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
