# Generated by Django 6.0.6 on 2026-06-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_userprofile_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
