# Generated by Django 6.0.6 on 2026-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprofile_full_name_alter_userprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='microsoft_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
