"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#tj8&)d2)4=b97ae8j&gcxxoohe3&4+sq_rq*ss&qua1u^h&9_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


"""Security"""

CSRF_TRUSTED_ORIGINS = [
    "http://10.10.30.105:8000",
    "http://localhost:8000",
    "http://0.0.0.0:8000",
    "http://10.10.13.19:8070",
    "http://10.10.13.22:8070",
    "https://betopiadaily.shop",
    "https://server.betopiadaily.shop",
    "http://betopiadaily.shop",
    "http://server.betopiadaily.shop",
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://localhost:5173",
    "http://localhost:3000",
    "http://10.10.13.22:8070",
    "https://betopiadaily.shop",
    "https://server.betopiadaily.shop",
    "http://betopiadaily.shop",
    "http://server.betopiadaily.shop",
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

"""End of Security"""


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "django_ckeditor_5",
    "corsheaders",
    # Local apps
    "apps.utils",
    "apps.products",
    "apps.user",
    "apps.apis",
    "apps.site_settings",
    "apps.cart",
    "apps.checkout",
    "apps.dashboard",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Production Database
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "betopia_daily",
#         "USER": "betopia_daily_user",
#         "PASSWORD": "betopia_daily@123",
#         "HOST": "localhost",
#         "PORT": "5432",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


""" Internationalization """

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


""" Media and Static files (CSS, JavaScript, Images) """
STATIC_URL = "/static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
STATIC_ROOT = BASE_DIR / "staticfiles"

""" CKEditor5 Configuration """
CKEDITOR_5_CONFIGS = {
    "extends": {
        "toolbar": {
            "items": [
                "heading",
                "|",
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "|",
                "fontSize",
                "fontFamily",
                "fontColor",
                "fontBackgroundColor",
                "|",
                "alignment",
                "|",
                "numberedList",
                "bulletedList",
                "todoList",
                "|",
                "outdent",
                "indent",
                "|",
                "link",
                "insertImage",
                "blockQuote",
                "insertTable",
                "mediaEmbed",
                "codeBlock",
                "|",
                "horizontalLine",
                "specialCharacters",
                "|",
                "subscript",
                "superscript",
                "|",
                "removeFormat",
                "|",
                "undo",
                "redo",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "imageTitle",
                "|",
                "imageStyle:inline",
                "imageStyle:block",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "linkImage",
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableCellProperties",
                "tableProperties",
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "fontFamily": {
            "options": [
                "default",
                "Arial",
                "Courier New",
                "Georgia",
                "Lucida Sans Unicode",
                "Tahoma",
                "Times New Roman",
                "Trebuchet MS",
                "Verdana",
            ],
            "supportAllValues": True,
        },
        "fontSize": {
            "options": [10, 12, 14, "default", 18, 20, 24, 28, 36],
            "supportAllValues": True,
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        },
    }
}

""" Rate Limiting Configuration """
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": f"{os.getenv('RATE_LIMIT_ANON_PER_HOUR', '100')}/hour",
        "user": f"{os.getenv('RATE_LIMIT_USER_PER_HOUR', '1000')}/hour",
    },
}


MS_SSO_CLIENT_ID = os.environ.get(
    "MS_SSO_CLIENT_ID", "97fadfc8-200e-42d9-b112-787b091a432c"
)
MS_SSO_TENANT_ID = os.environ.get(
    "MS_SSO_TENANT_ID", "0d2c1116-d7c2-4380-b446-78e71d8f2465"
)
GROCERY_ELIGIBILITY_API_KEY = os.environ.get(
    "GROCERY_ELIGIBILITY_API_KEY",
    "YCYmg55iVZMTfakV1McpZJ-MmKausRCo9gFjWNTAU4p9lZ3g",
)

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}
